MemeIO/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('MemeIOX.urls')),
]

MemeIOX/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'MemeIOX'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('topic/<int:topic_id>', views.topic, name='topic'),
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MemeIOX/models.py
from django.db import models
# Create your models here.
class Topic(models.Model):

    title = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'topics'

    def __str__(self):
        return self.title

class Entry(models.Model):

    title = models.CharField(max_length=300, null=True)
    entry_file = models.ImageField(null=True, default="https://placehold.co/500x500")
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True)
    date_added = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.title[:50]

MemeIOX/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = '__all__'

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = '__all__'
        exclude = ['topic']

MemeIOX/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

from datetime import datetime

# Create your views here.
def index(req):
    topics = Topic.objects.order_by('-date_added')
    ctx = {'topics': topics}
    return render(req, 'index.html', ctx)

def topics(req):
    topics = Topic.objects.order_by('-date_added')
    ctx = {'topics': topics}
    return render(req, 'topics.html', ctx)

def new_topic(req):
    if req.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=req.POST)
        if form.is_valid():
            create_topic = form.save(commit=False)
            create_topic.save()
            print('Success!')
            return redirect('MemeIOX:topics')
    ctx = {'form': form}
    return render(req, 'new_topic.html', ctx)

def topic(req, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = Entry.objects.filter(topic=topic_id).order_by('-date_added')
    ctx = {'topic': topic, 'entries': entries}
    return render(req, 'topic.html', ctx)

def new_entry(req, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if req.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(req.POST, req.FILES)
        if form.is_valid():
            create_entry = form.cleaned_data
            Entry.objects.create(title=create_entry['title'], entry_file=create_entry['entry_file'], topic=Topic.objects.get(id=topic_id), date_added=datetime.now())
            return redirect('MemeIOX:topic', topic_id)
    ctx = {'topic': topic, 'form' : form}
    return render(req, 'new_entry.html', ctx)

MemeIOX/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meme.io - Post Your Memes Here</title>

    <link rel="stylesheet" href="../static/base.css">
    <link rel="stylesheet" href="../static/index.css">
    <link rel="stylesheet" href="../static/topics.css">
    <link rel="stylesheet" href="../static/topic.css">
    <link rel="stylesheet" href="../static/new_topic.css">
    <link rel="stylesheet" href="../static/new_entry.css">
    <!-- <link rel="stylesheet" href="../../MemeIOXUsers/static/login.css">
    <link rel="stylesheet" href="../../MemeIOXUsers/static/register.css"> -->

</head>
<body>
    
    <div class="view-wrapper">

        <div class="view-wrapper-sidebar">
            <a href="{% url 'MemeIOX:index' %}">Home</a>
            <a href="{% url 'MemeIOX:topics' %}">Topics</a>
        </div>

        <div class="view-wrapper-content">{% block content %}{% endblock content %}</div>

    </div>

</body>
</html>

MemeIOX/templates/index.html
{% extends "base.html" %}

{% block content %}

    <div class="index-intro-wrap">
        <h2>Welcome to MemeIO!</h2>
        <p>Feel Free to Share Memes Here~</p>
    </div>

    <div class="index-topic-catalog">
        <h4>Browse Our Topics</h4>
        {% for topic in topics %}
            <a class="index-topic-catalog-link" href="{% url 'MemeIOX:topic' topic.id %}">{{ topic }}</a>
        {% empty %}
            <p class="empty-text-yet">There are no topics... YET</p>
        {% endfor %}
    </div>
    
    <a class="index-create-btn" href="{% url 'MemeIOX:new_topic' %}">Create New Topic</a>

{% endblock content %}

MemeIOX/templates/new_entry.html
{% extends "base.html" %}

{% block content %}

    <div class="newentry-intro-wrap">
        <h3>Add a Post to <a href="{% url 'MemeIOX:topic' topic.id %}">"{{ topic }}"</a></h3>
        <p>Posting Made Easy...</p>
    </div>

    <div class="newentry-form-wrap">
        <form enctype="multipart/form-data" action="{% url 'MemeIOX:new_entry' topic.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">Add Entry</button>
        </form>
    </div>

{% endblock content %}

MemeIOX/templates/new_topic.html
{% extends "base.html" %}

{% block content %}

    <div class="newtopic-intro-wrap">
        <h3>Add a New Topic:</h3>
        <p>Creating a Topic is this easy...</p>
    </div>

    <div class="newtopic-form-wrap">
        <form action="{% url 'MemeIOX:new_topic' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">Add Topic</button>
        </form>
    </div>

{% endblock content %}  

MemeIOX/templates/topic.html
{% extends "base.html" %}

{% block content %}

    <div class="topic-intro-wrap">
        <h3>Welcome to "{{ topic }}"</h3>
        <p>This topic has been created on {{ topic.date_added }}</p>
    </div>

    <div class="topic-topic-wrap">
        {% for entry in entries %}
            <hr>
            <div class="topic-entry-wrapper">
                <h4>{{ entry }}</h4>
                <img src="{{ entry.entry_file.url }}" alt="image failed to load" width="200px" height="auto">
            </div>
        {% empty %}
            <hr>
            <p class="empty-text-yet">There are no entries... YET</p>
        {% endfor %}
        <hr>
    </div>

    <a class="topic-create-btn" href="{% url 'MemeIOX:new_entry' topic.id %}">Create New Entry</a>

{% endblock content %}

MemeIOX/templates/topics.html
{% extends "base.html" %}

{% block content %}

    <div class="topics-intro-wrap">
        <h3>MemeIO's Topics</h3>
        <p>Can't see your interests? Add One!</p>
    </div>

    <div class="topics-topics-wrap">
        {% for topic in topics %}
            <a class="topics-topics-wrap-link" href="{% url 'MemeIOX:topic' topic.id %}">{{ topic }}</a>
        {% empty %}
            <p class="empty-text-yet">There are no topics YET</p>
        {% endfor %}
    </div>

    <a class="topics-create-btn" href="{% url 'MemeIOX:new_topic' %}">Create New Topic</a>

{% endblock content %}